"""Add body_html column to Post model

Revision ID: 220a62d456
Revises: da9dc37ad0
Create Date: 2014-08-29 23:00:47.816132

"""

# revision identifiers, used by Alembic.
revision = '220a62d456'
down_revision = 'da9dc37ad0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
