"""add confirmamed field to User model

Revision ID: 3a1e4e7c480
Revises: 2bf44055f1c
Create Date: 2014-08-24 09:47:28.538033

"""

# revision identifiers, used by Alembic.
revision = '3a1e4e7c480'
down_revision = '2bf44055f1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
